Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -100,18 +100,6 @@ jobs:
         UPDATED_URI="${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA }}"
         sed "s|REPLACE_ME|$UPDATED_URI|g" ecs-task-def.json > final-task-def.json
 
-    - name: Register ECS task definition
-      run: |
-        TASK_DEF_ARN=$(aws ecs register-task-definition \
-          --cli-input-json file://final-task-def.json \
-          --query 'taskDefinition.taskDefinitionArn' \
-          --output text)
-        if [ -z "$TASK_DEF_ARN" ]; then
-          echo "Task definition registration failed."
-          exit 1
-        fi
-        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
-
     - name: Stop existing ECS tasks
       run: |
         TASK_ARN=$(aws ecs list-tasks \
@@ -126,6 +114,33 @@ jobs:
         else
           echo "No running tasks found."
         fi
+        
+    - name: Register ECS task definition
+      run: |
+        TASK_DEF_ARN=$(aws ecs register-task-definition \
+          --cli-input-json file://final-task-def.json \
+          --query 'taskDefinition.taskDefinitionArn' \
+          --output text)
+        if [ -z "$TASK_DEF_ARN" ]; then
+          echo "Task definition registration failed."
+          exit 1
+        fi
+        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
+
+    - name: Deregister old task definitions
+      run: |
+        FAMILY="${TASK_DEF_FAMILY}"
+        OLD_REVISIONS=$(aws ecs list-task-definitions \
+          --family-prefix $FAMILY \
+          --status ACTIVE \
+          --sort DESC \
+          --query 'taskDefinitionArns[1:]' \
+          --output text)
+
+        for TD_ARN in $OLD_REVISIONS; do
+          echo "Deregistering $TD_ARN"
+          aws ecs deregister-task-definition --task-definition $TD_ARN
+        done
         
     - name: Create or update ECS service
       run: |
