Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -53,10 +53,10 @@ jobs:
 
     - name: Create ECS cluster if not exists
       run: |
-        CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME \
-        --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
+        CLUSTER_CHECK=$(aws ecs describe-clusters --clusters $CLUSTER_NAME \
+        --query "clusters[0].status" --output text || echo "MISSING")
 
-        if [ "$CLUSTER_EXISTS" = "MISSING" ] || [ "$CLUSTER_EXISTS" = "INACTIVE" ]; then
+        if [ "$CLUSTER_CHECK" = "MISSING" ] || [ "$CLUSTER_CHECK" = "None" ]; then
           echo "Cluster not found. Creating ECS cluster..."
           aws ecs create-cluster --cluster-name $CLUSTER_NAME
         else
