Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -5,6 +5,15 @@ on:
     branches:
       - master  
 
+env:
+  CLUSTER_NAME: demoec2
+  SERVICE_NAME: demo-service
+  TASK_DEF_FAMILY: demo-task
+  CONTAINER_NAME: demo-container
+  #ECR_REPO: your-ecr-repo-name
+  IMAGE_TAG: latest6
+
+  
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -37,8 +46,53 @@ jobs:
 
     - name: Build, tag, and push Docker image to ECR
       run: |
-        IMAGE_TAG=latest
+        #IMAGE_TAG=latest123
         docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
         docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
 
+
+    - name: Create ECS cluster if not exists
+      run: |
+        if ! aws ecs describe-clusters --clusters $CLUSTER_NAME | grep $CLUSTER_NAME; then
+          aws ecs create-cluster --cluster-name $CLUSTER_NAME
+        fi
+
+    - name: Prepare updated task definition
+      id: task-def
+      run: |
+        IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
+        sed "s|REPLACE_ME|$IMAGE_URI|g" ecs-task-def.json > final-task-def.json
+
+    - name: Register new task definition
+      run: |
+        TASK_DEF_ARN=$(aws ecs register-task-definition \
+          --cli-input-json file://final-task-def.json \
+          --query 'taskDefinition.taskDefinitionArn' \
+          --output text)
+        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
+
+    - name: Create or update ECS service
+      run: |
+        SERVICE_EXISTS=$(aws ecs describe-services \
+          --cluster $CLUSTER_NAME \
+          --services $SERVICE_NAME \
+          --query "services[0].status" \
+          --output text || echo "MISSING")
+
+        if [ "$SERVICE_EXISTS" == "ACTIVE" ]; then
+          echo "Updating ECS service..."
+          aws ecs update-service \
+            --cluster $CLUSTER_NAME \
+            --service $SERVICE_NAME \
+            --task-definition $TASK_DEF_ARN \
+            --force-new-deployment
+        else
+          echo "Creating ECS service..."
+          aws ecs create-service \
+            --cluster $CLUSTER_NAME \
+            --service-name $SERVICE_NAME \
+            --task-definition $TASK_DEF_ARN \
+            --launch-type EC2 \
+            --desired-count 1
+        fi
 
