Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -65,11 +65,10 @@ jobs:
 
     - name: Create ECS cluster if not exists
       run: |
-        CLUSTER_CHECK=$(aws ecs describe-clusters --clusters $CLUSTER_NAME \
-        --query "clusters[0].status" --output text || echo "MISSING")
+        CLUSTER_CHECK=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --query "clusters[0].status" --output text || echo "MISSING")
 
         if [ "$CLUSTER_CHECK" = "MISSING" ] || [ "$CLUSTER_CHECK" = "None" ]; then
-          echo "Cluster not found. Creating ECS cluster..."
+          echo "$CLUSTER_NAME Cluster not found. Creating $CLUSTER_NAME ECS cluster..."
           aws ecs create-cluster --cluster-name $CLUSTER_NAME
         else
           echo "ECS cluster '$CLUSTER_NAME' already exists."
